name: Build
on:
  push:
  workflow_dispatch:
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sirabien/rddns:dev-test
      -
        name: Extract binary
        uses: shrink/actions-docker-extract@v3
        with:
          image: sirabien/rddns:dev-test
          path: /rddns
          destination: dist/rddns-linux-amd64
      - 
        name: Upload Dist
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist
          if-no-files-found: error